



<input type="hidden" name="struts.token.name" value="token" />
<input type="hidden" name="token" value="I9S34OL10Y225AVGQ5410W8G7JBI1U25" />



    <div class="modal__title">Sign In</div>

    <button id="facebookLoginButtonLogin" class="waves-effect waves-light btn btn--facebook modal-register__facebook modal-close" data-url="https://www.facebook.com/dialog/oauth?client_id=2417639858520111&amp;redirect_uri=https%3A%2F%2Fnew.propstore.com%2Fajax%2FfacebookLoginCallback.action&amp;scope=email" type="button">
        <i class='icon'>
            <svg>
                <use xlink:href="#facebook"></use>
            </svg>
        </i>
        <span class='btn__title'>Sign in with Facebook</span>
    </button>

    <div class="input-field input-field--label ">
        <input type="email" name="email" value="" id="email" placeholder="Please Enter"/>
        <label>Email</label>
        <div class="input-field__helper"></div>
    </div>

    <div class="input-field input-field--label ">
        <input type="password" name="password" id="password" placeholder="Please Enter"/>
        <label>Password</label>
        <div class="input-field__helper"></div>
    </div>

    <div class="modal-register__remember">
        <label class="checkbox__label">
            <input type="checkbox" name="rememberMe" value="true" id="rememberMe" class="filled-in"/><input type="hidden" id="__checkbox_rememberMe" name="__checkbox_rememberMe" value="true" />
            <span>Remember me</span>
        </label>
    </div>

    <div class="modal-register__forgot">
        <a class="btn-flat btn--link modal-trigger modal-close" href="#modal-password">Forgot password?</a>
    </div>

    <button type="submit" class="waves-effect waves-light btn modal-register__submit">
        <span class='btn__title'>Sign in</span>
        <i class='icon'>
            <svg>
                <use xlink:href="#arrow-right"></use>
            </svg>
        </i>
        <div class="preloader-wrapper active">
            <div class="spinner-layer spinner-white-only">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </button>

    <div class="modal-register__switch">
        Don’t have an account? <a class="modal-trigger modal-close" href="#modal-register">Register</a>
    </div>

